import React from 'react';
import 'boxicons'

const Shop = () => {
  return (
    <React.Fragment>
      {/* <img className="check" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABqUlEQVRIS72V3VXCQBCF78QCtAMhFCBWoHaAFUgHQngmMfBMiBWoFYgVaAnhXdfQARRAxrNxk5Nf8uPBfco5mb3fndnZWcKRFx1ZH5UAozcbgnFFoD6D+9IQgTwGe6zxavlpvR0yWQqY9OYDZl4C6FRk6RPRePE1XRXFFQLGuu0S6L5h+VxHmOPsnhygpXioy+DHpbBGSUgKoMry2tB5KpyIbpPlSgEMfeYDOP8LAIDvCLMbacQA1S1PDcR3ALsAWbm6J7KIAZPu/JmJ72oCdkGwv3Z92zN0+yELIaaXxfd0+NvSahn6zANwUQMQi486Vl/TTt4BnKUPlryFmF5mAZwXZxsg2RWn6l+leKThCDM0n8wgA2DbEdaDcvkhg6OylDlPGiwCZEu0DYL9jayzFJSbo++ismSyXzvCVGNF/Sk55Bgiw+o4D8tSdMgHLlkIkRtrOA/tJi9b3Yu2VYmmuqWk4zaOMOMB+b+jQjo66rCLUm4DKZqkqXuQrac6dLfG8NsQ0ajRg5OESRACDJjC5zIaJWti8qBhVSacm6Y1ZlCrkMpHv5VqYtMPKQvZGS6IiYgAAAAASUVORK5CYII=" alt=""/> */}
      <img className="check" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABUUlEQVRIS72VYVEDMRCFvyoABxQFBQVQB6CgdQBVQFEAKAAUQBUUCeAAHIACOm8m6ezt7fWSMkdm8uuy79u87O6NGHiNBtanBDAHzoCTtJXTe9qvwGpXkrsAF8AdMO655SewAARrrS7APXBVaZ9iBGqsCLCPeBZ9AK4twQNky0tl5v74pbXLA+Tn0R8B0jjOGhaganmsEP8BZOdNELO9hQU8AbNCgMTPU6kuA8gzoIQbfaDanhQArLh6Yw0cujhpnXrAbyB+m6riIH0rEW/Yby3yAInr+sryLUVlW7oyb1WoBXiLvoFp8lmCWjpTIv6Rx0rfI1uIACXiOhc+cleTZYgCoweN6iIsUx3sajRBtHy1ROJfdkD++6hQRoMOu3zlfSCtSeobzfupRxeob/jJc43oqh+OhQmkrRLNo0R1rp6QaCgcTdOCMVR/pOSnX69qIjbmMUYZlWQeyQAAAABJRU5ErkJggg==" alt=""/>
    </React.Fragment>
  );
}
export default Shop;